ida extract library funcs identified via flirt
fireeye/capa pull request #661
Opened 2021-06-28 12:13 UTC by mr-tz

closes #658

### Checklist

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

2021-06-28 16:09 UTC, mike-hunhoff requested changes
Looks good, thank you for coding this! Some minor changes suggested, otherwise LGTM 🚀

2021-06-28 16:09 UTC, mike-hunhoff commented on capa/features/extractors/ida/insn.py
> +    targets = list(idautils.CodeRefsFrom(insn.ea, False))
```suggestion
    targets = tuple(idautils.CodeRefsFrom(insn.ea, False))
```

2021-06-28 16:09 UTC, mike-hunhoff commented on capa/features/extractors/ida/insn.py
> +    if idaapi.get_func(target).flags & idaapi.FUNC_LIB:
```suggestion
    if target_func.flags & idaapi.FUNC_LIB:
```

2021-06-28 16:09 UTC, mike-hunhoff commented on capa/features/extractors/ida/insn.py
> +        name = idaapi.get_name(target)
```suggestion
        name = idaapi.get_name(target_func.start_ea)
```

2021-06-28 16:09 UTC, mike-hunhoff commented on capa/features/extractors/ida/insn.py
> +    if not insn.get_canon_mnem() in ("call", "jmp"):
nice catch!

2021-06-29 07:22 UTC, mr-tz commented
thanks for the feedback, Mike!

2021-06-29 07:23 UTC, merged